### ISSUE TITLE
Missing examples and download links/builder

### ISSUE THREAD

**Issue by jeff-crosby** [DataTables/StateRestore#1]
Hello, I'd like to give this extension a try, but I noticed the example page for it on the DataTables site is blank at https://datatables.net/extensions/staterestore/examples 

Also, the page at https://datatables.net/extensions/staterestore/ points to https://datatables.net/download/release as a place to obtain CDN links for it, but this extension is not listed on that page. It also points to the Download Package page at https://datatables.net/download/packages, but this extension is not listed there either.

Has this extension been folded into the main table library?

Thanks!

**Comment by AllanJard** [comment]
Hi! Sorry - I hadn't meant to put the site update out with references to StateRestore yet! I hope to get it released properly tomorrow.

**Comment by AllanJard** [comment]
That's 1.0.0 all tagged up and released and Sandy's blog post [on introducing StateRestore is now online](https://datatables.net/blog/2021-11-26).

**Comment by jeff-crosby** [comment]
Thanks so much! I'm excited to try it out.
