### ISSUE TITLE
activeStates and button highlighting do not work for predefined states

### ISSUE THREAD

**Issue by gouldner** [DataTables/StateRestore#3]
See this jsfiddle to see the issue.   Using buttons 2.1.1 and stateRestore 1.0.1

If you create some view manually you will see they work fine.   They highlight when selected and the title updates.
However, when you select either of the two predefined views they don't highlight as active (I enhanced to make active green) and the Active States bar doesn't update.

https://jsfiddle.net/gouldner/m1yjs6bp/

**Comment by SandyDatatables** [comment]
Hi @gouldner ,

Something isn't right there. I've raised an issue internally (DD-2397 for my reference) and will report back here when there is an update.

Thanks,
Sandy

**Comment by SandyDatatables** [comment]
Hi @gouldner ,

That should be the issue fixed now as you can see at [this example](https://jsfiddle.net/b25xa1pm/1/ "this example"). This will be available in the next StateRestore release which we hope will be in the next few weeks. Until then you can access the fix from the [nightly builds](https://nightly.datatables.net/staterestore/js/dataTables.stateRestore.js "nightly builds").

Thanks,
Sandy
